FROM node:16-alpine

LABEL version="1.0"
LABEL description="This is the base docker image for the stx-service API."
LABEL maintainer = ["adetola013@gmail.com"]

WORKDIR /app
COPY /stx-service/package*.json ./
RUN npm install
COPY /stx-service/ .
EXPOSE 5000

CMD ["npm", "run", "dev"]